package br.udesc.esag.participactbrasil.domain.enums;

public enum UniSchool {
    AGRARIA_E_MEDICINA_VETERINARIA, ECONOMIA_MANAGEMENT_E_STATISTICA, FARMACIA_BIOTECNOLOGIE_E_SCIENZE_MOTORIE, GIURISPRUDENZA, INGEGNERIA_E_ARCHITETTURA, LETTERE_E_BENI_CULTURALI, LINGUE_E_LETTERATURE_TRADUZIONE_E_INTERPRETAZIONE, MEDICINA_E_CHIRURGIA, PSICOLOGIA_E_SCIENZE_DELLA_FORMAZIONE, SCIENZE, SCIENZE_POLITICHE;
}
