package br.com.participact.participactbrasil.modules.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "CAMPAIGN_STATUS".
 */
@Entity
public class CampaignStatus {

    @Id
    private Long campaignId;
    private Boolean ended;
    private Boolean completed;
    private Integer campaignProgress;
    private Integer campaignDateProgress;

    @Generated
    public CampaignStatus() {
    }

    public CampaignStatus(Long campaignId) {
        this.campaignId = campaignId;
    }

    @Generated
    public CampaignStatus(Long campaignId, Boolean ended, Boolean completed, Integer campaignProgress, Integer campaignDateProgress) {
        this.campaignId = campaignId;
        this.ended = ended;
        this.completed = completed;
        this.campaignProgress = campaignProgress;
        this.campaignDateProgress = campaignDateProgress;
    }

    public Long getCampaignId() {
        return campaignId;
    }

    public void setCampaignId(Long campaignId) {
        this.campaignId = campaignId;
    }

    public Boolean getEnded() {
        return ended;
    }

    public void setEnded(Boolean ended) {
        this.ended = ended;
    }

    public Boolean getCompleted() {
        return completed;
    }

    public void setCompleted(Boolean completed) {
        this.completed = completed;
    }

    public Integer getCampaignProgress() {
        return campaignProgress;
    }

    public void setCampaignProgress(Integer campaignProgress) {
        this.campaignProgress = campaignProgress;
    }

    public Integer getCampaignDateProgress() {
        return campaignDateProgress;
    }

    public void setCampaignDateProgress(Integer campaignDateProgress) {
        this.campaignDateProgress = campaignDateProgress;
    }

}
