package br.com.participact.participactbrasil.modules.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "PANOTIFICATION".
 */
@Entity
public class PANotification {

    @Id
    private Long id;
    private String message;
    private Boolean read;

    @Generated
    public PANotification() {
    }

    public PANotification(Long id) {
        this.id = id;
    }

    @Generated
    public PANotification(Long id, String message, Boolean read) {
        this.id = id;
        this.message = message;
        this.read = read;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    public Boolean getRead() {
        return read;
    }

    public void setRead(Boolean read) {
        this.read = read;
    }

}
