package br.com.participact.participactbrasil.modules.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "PENDING_REQUEST".
 */
@Entity
public class PendingRequest {

    @Id(autoincrement = true)
    private Long id;
    private Long campaignId;
    private String requestType;

    @Generated
    public PendingRequest() {
    }

    public PendingRequest(Long id) {
        this.id = id;
    }

    @Generated
    public PendingRequest(Long id, Long campaignId, String requestType) {
        this.id = id;
        this.campaignId = campaignId;
        this.requestType = requestType;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getCampaignId() {
        return campaignId;
    }

    public void setCampaignId(Long campaignId) {
        this.campaignId = campaignId;
    }

    public String getRequestType() {
        return requestType;
    }

    public void setRequestType(String requestType) {
        this.requestType = requestType;
    }

}
