package br.com.participact.participactbrasil.modules.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "PHOTO".
*/
public class PhotoDao extends AbstractDao<Photo, Long> {

    public static final String TABLENAME = "PHOTO";

    /**
     * Properties of entity Photo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Filename = new Property(1, String.class, "filename", false, "FILENAME");
        public final static Property Latitude = new Property(2, Double.class, "latitude", false, "LATITUDE");
        public final static Property Longitude = new Property(3, Double.class, "longitude", false, "LONGITUDE");
        public final static Property Provider = new Property(4, String.class, "provider", false, "PROVIDER");
        public final static Property Uploaded = new Property(5, Boolean.class, "uploaded", false, "UPLOADED");
        public final static Property ReadyToUpload = new Property(6, Boolean.class, "readyToUpload", false, "READY_TO_UPLOAD");
        public final static Property QuestionId = new Property(7, Long.class, "questionId", false, "QUESTION_ID");
        public final static Property ActionId = new Property(8, Long.class, "actionId", false, "ACTION_ID");
        public final static Property CampaignId = new Property(9, Long.class, "campaignId", false, "CAMPAIGN_ID");
        public final static Property DateUploaded = new Property(10, java.util.Date.class, "dateUploaded", false, "DATE_UPLOADED");
        public final static Property IpAddress = new Property(11, String.class, "ipAddress", false, "IP_ADDRESS");
        public final static Property AnswerGroupId = new Property(12, Long.class, "answerGroupId", false, "ANSWER_GROUP_ID");
    }


    public PhotoDao(DaoConfig config) {
        super(config);
    }
    
    public PhotoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"PHOTO\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"FILENAME\" TEXT," + // 1: filename
                "\"LATITUDE\" REAL," + // 2: latitude
                "\"LONGITUDE\" REAL," + // 3: longitude
                "\"PROVIDER\" TEXT," + // 4: provider
                "\"UPLOADED\" INTEGER," + // 5: uploaded
                "\"READY_TO_UPLOAD\" INTEGER," + // 6: readyToUpload
                "\"QUESTION_ID\" INTEGER," + // 7: questionId
                "\"ACTION_ID\" INTEGER," + // 8: actionId
                "\"CAMPAIGN_ID\" INTEGER," + // 9: campaignId
                "\"DATE_UPLOADED\" INTEGER," + // 10: dateUploaded
                "\"IP_ADDRESS\" TEXT," + // 11: ipAddress
                "\"ANSWER_GROUP_ID\" INTEGER);"); // 12: answerGroupId
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"PHOTO\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Photo entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String filename = entity.getFilename();
        if (filename != null) {
            stmt.bindString(2, filename);
        }
 
        Double latitude = entity.getLatitude();
        if (latitude != null) {
            stmt.bindDouble(3, latitude);
        }
 
        Double longitude = entity.getLongitude();
        if (longitude != null) {
            stmt.bindDouble(4, longitude);
        }
 
        String provider = entity.getProvider();
        if (provider != null) {
            stmt.bindString(5, provider);
        }
 
        Boolean uploaded = entity.getUploaded();
        if (uploaded != null) {
            stmt.bindLong(6, uploaded ? 1L: 0L);
        }
 
        Boolean readyToUpload = entity.getReadyToUpload();
        if (readyToUpload != null) {
            stmt.bindLong(7, readyToUpload ? 1L: 0L);
        }
 
        Long questionId = entity.getQuestionId();
        if (questionId != null) {
            stmt.bindLong(8, questionId);
        }
 
        Long actionId = entity.getActionId();
        if (actionId != null) {
            stmt.bindLong(9, actionId);
        }
 
        Long campaignId = entity.getCampaignId();
        if (campaignId != null) {
            stmt.bindLong(10, campaignId);
        }
 
        java.util.Date dateUploaded = entity.getDateUploaded();
        if (dateUploaded != null) {
            stmt.bindLong(11, dateUploaded.getTime());
        }
 
        String ipAddress = entity.getIpAddress();
        if (ipAddress != null) {
            stmt.bindString(12, ipAddress);
        }
 
        Long answerGroupId = entity.getAnswerGroupId();
        if (answerGroupId != null) {
            stmt.bindLong(13, answerGroupId);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Photo entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String filename = entity.getFilename();
        if (filename != null) {
            stmt.bindString(2, filename);
        }
 
        Double latitude = entity.getLatitude();
        if (latitude != null) {
            stmt.bindDouble(3, latitude);
        }
 
        Double longitude = entity.getLongitude();
        if (longitude != null) {
            stmt.bindDouble(4, longitude);
        }
 
        String provider = entity.getProvider();
        if (provider != null) {
            stmt.bindString(5, provider);
        }
 
        Boolean uploaded = entity.getUploaded();
        if (uploaded != null) {
            stmt.bindLong(6, uploaded ? 1L: 0L);
        }
 
        Boolean readyToUpload = entity.getReadyToUpload();
        if (readyToUpload != null) {
            stmt.bindLong(7, readyToUpload ? 1L: 0L);
        }
 
        Long questionId = entity.getQuestionId();
        if (questionId != null) {
            stmt.bindLong(8, questionId);
        }
 
        Long actionId = entity.getActionId();
        if (actionId != null) {
            stmt.bindLong(9, actionId);
        }
 
        Long campaignId = entity.getCampaignId();
        if (campaignId != null) {
            stmt.bindLong(10, campaignId);
        }
 
        java.util.Date dateUploaded = entity.getDateUploaded();
        if (dateUploaded != null) {
            stmt.bindLong(11, dateUploaded.getTime());
        }
 
        String ipAddress = entity.getIpAddress();
        if (ipAddress != null) {
            stmt.bindString(12, ipAddress);
        }
 
        Long answerGroupId = entity.getAnswerGroupId();
        if (answerGroupId != null) {
            stmt.bindLong(13, answerGroupId);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Photo readEntity(Cursor cursor, int offset) {
        Photo entity = new Photo( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // filename
            cursor.isNull(offset + 2) ? null : cursor.getDouble(offset + 2), // latitude
            cursor.isNull(offset + 3) ? null : cursor.getDouble(offset + 3), // longitude
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // provider
            cursor.isNull(offset + 5) ? null : cursor.getShort(offset + 5) != 0, // uploaded
            cursor.isNull(offset + 6) ? null : cursor.getShort(offset + 6) != 0, // readyToUpload
            cursor.isNull(offset + 7) ? null : cursor.getLong(offset + 7), // questionId
            cursor.isNull(offset + 8) ? null : cursor.getLong(offset + 8), // actionId
            cursor.isNull(offset + 9) ? null : cursor.getLong(offset + 9), // campaignId
            cursor.isNull(offset + 10) ? null : new java.util.Date(cursor.getLong(offset + 10)), // dateUploaded
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // ipAddress
            cursor.isNull(offset + 12) ? null : cursor.getLong(offset + 12) // answerGroupId
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Photo entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setFilename(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setLatitude(cursor.isNull(offset + 2) ? null : cursor.getDouble(offset + 2));
        entity.setLongitude(cursor.isNull(offset + 3) ? null : cursor.getDouble(offset + 3));
        entity.setProvider(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setUploaded(cursor.isNull(offset + 5) ? null : cursor.getShort(offset + 5) != 0);
        entity.setReadyToUpload(cursor.isNull(offset + 6) ? null : cursor.getShort(offset + 6) != 0);
        entity.setQuestionId(cursor.isNull(offset + 7) ? null : cursor.getLong(offset + 7));
        entity.setActionId(cursor.isNull(offset + 8) ? null : cursor.getLong(offset + 8));
        entity.setCampaignId(cursor.isNull(offset + 9) ? null : cursor.getLong(offset + 9));
        entity.setDateUploaded(cursor.isNull(offset + 10) ? null : new java.util.Date(cursor.getLong(offset + 10)));
        entity.setIpAddress(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setAnswerGroupId(cursor.isNull(offset + 12) ? null : cursor.getLong(offset + 12));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Photo entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Photo entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Photo entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
