package br.com.participact.participactbrasil.modules.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "QUESTION_OPTION".
 */
import com.google.gson.annotations.SerializedName;
@Entity
public class QuestionOption {

    @Id
    private Long id;
    @SerializedName("answerDescription")
    private String option;
    @SerializedName("answerOrder")
    private Integer order;
    private Long targetId;
    private Long questionId;

    @Generated
    public QuestionOption() {
    }

    public QuestionOption(Long id) {
        this.id = id;
    }

    @Generated
    public QuestionOption(Long id, String option, Integer order, Long targetId, Long questionId) {
        this.id = id;
        this.option = option;
        this.order = order;
        this.targetId = targetId;
        this.questionId = questionId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getOption() {
        return option;
    }

    public void setOption(String option) {
        this.option = option;
    }

    public Integer getOrder() {
        return order;
    }

    public void setOrder(Integer order) {
        this.order = order;
    }

    public Long getTargetId() {
        return targetId;
    }

    public void setTargetId(Long targetId) {
        this.targetId = targetId;
    }

    public Long getQuestionId() {
        return questionId;
    }

    public void setQuestionId(Long questionId) {
        this.questionId = questionId;
    }

}
