package br.com.participact.participactbrasil.modules.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "SENSOR".
 */
@Entity
public class Sensor {

    @Id(autoincrement = true)
    private Long id;
    private Integer pipelineTypeValue;
    private String data;
    private java.util.Date dateWhen;
    private Boolean uploaded;
    private java.util.Date dateUploaded;

    @Generated
    public Sensor() {
    }

    public Sensor(Long id) {
        this.id = id;
    }

    @Generated
    public Sensor(Long id, Integer pipelineTypeValue, String data, java.util.Date dateWhen, Boolean uploaded, java.util.Date dateUploaded) {
        this.id = id;
        this.pipelineTypeValue = pipelineTypeValue;
        this.data = data;
        this.dateWhen = dateWhen;
        this.uploaded = uploaded;
        this.dateUploaded = dateUploaded;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getPipelineTypeValue() {
        return pipelineTypeValue;
    }

    public void setPipelineTypeValue(Integer pipelineTypeValue) {
        this.pipelineTypeValue = pipelineTypeValue;
    }

    public String getData() {
        return data;
    }

    public void setData(String data) {
        this.data = data;
    }

    public java.util.Date getDateWhen() {
        return dateWhen;
    }

    public void setDateWhen(java.util.Date dateWhen) {
        this.dateWhen = dateWhen;
    }

    public Boolean getUploaded() {
        return uploaded;
    }

    public void setUploaded(Boolean uploaded) {
        this.uploaded = uploaded;
    }

    public java.util.Date getDateUploaded() {
        return dateUploaded;
    }

    public void setDateUploaded(java.util.Date dateUploaded) {
        this.dateUploaded = dateUploaded;
    }

}
