package br.com.participact.participactbrasil.modules.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "UPFILE_DB".
 */
@Entity
public class UPFileDB {

    @Id(autoincrement = true)
    private Long id;
    private String filename;
    private String filePath;
    private Long reportId;
    private Integer duration;
    private String type;
    private Boolean uploaded;
    private java.util.Date dateUploaded;

    @Generated
    public UPFileDB() {
    }

    public UPFileDB(Long id) {
        this.id = id;
    }

    @Generated
    public UPFileDB(Long id, String filename, String filePath, Long reportId, Integer duration, String type, Boolean uploaded, java.util.Date dateUploaded) {
        this.id = id;
        this.filename = filename;
        this.filePath = filePath;
        this.reportId = reportId;
        this.duration = duration;
        this.type = type;
        this.uploaded = uploaded;
        this.dateUploaded = dateUploaded;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getFilename() {
        return filename;
    }

    public void setFilename(String filename) {
        this.filename = filename;
    }

    public String getFilePath() {
        return filePath;
    }

    public void setFilePath(String filePath) {
        this.filePath = filePath;
    }

    public Long getReportId() {
        return reportId;
    }

    public void setReportId(Long reportId) {
        this.reportId = reportId;
    }

    public Integer getDuration() {
        return duration;
    }

    public void setDuration(Integer duration) {
        this.duration = duration;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public Boolean getUploaded() {
        return uploaded;
    }

    public void setUploaded(Boolean uploaded) {
        this.uploaded = uploaded;
    }

    public java.util.Date getDateUploaded() {
        return dateUploaded;
    }

    public void setDateUploaded(java.util.Date dateUploaded) {
        this.dateUploaded = dateUploaded;
    }

}
