package br.com.participact.participactbrasil.modules.support;

import java.util.Arrays;
import java.util.List;

public class PALists {

    public static final List<String> educations = Arrays.asList(
            "Ensino Fundamental",
            "Ensino Médio",
            "Superior",
            "Pós Graduação"
    );

    public static final List<String> universities = Arrays.asList(
            "ABMDP II - Academia de Bombeiro Militar Dom Pedro II",
            "Academia de Polícia Militar de Minas Gerais",
            "ACE - Associação Catarinense de Ensino",
            "AEMS - Faculdades Integradas de Três Lagoas",
            "AESA - Anhanguera Educacional",
            "Aespi/Fapi",
            "AFA - Academia da Força Aérea",
            "ALFA - Faculdade Alves Faria",
            "ALIANÇA - Faculdade Aliança",
            "AMAN - Academia Militar de Agulhas Negras",
            "Anhanguera - Faculdade Anhanguera",
            "APMBB - Academia de Polícia Militar do Barro Branco",
            "APMDJVI - Academia de Polícia Militar Dom João VI",
            "ASMEC - Associação Sul Mineira de Educação e Cultura",
            "AVEC - Associação Vilhenense de Educação e Cultura",
            "BANDTEC - Faculdade de Tecnologia Bandeirantes",
            "BENNETT - Instituto Metodista BENNETT",
            "BSP - Business School São Paulo",
            "CASTELLI - Escola Superior de Hotelaria Castelli",
            "CATHEDRAL - Faculdades Cathedral-Barra do Garças",
            "CBM - Centro Universitário Barão de Mauá",
            "CEAMA - Centro de Educação da Amazônia",
            "CECON - Centro Educacional Conceição Nunes",
            "CEFET-MG - Centro Federal de Educação Tecnológica de Minas Gerais",
            "CEFET/RJ - Centro Federal de Educação Tecnológica Celso Suckow da Fonseca",
            "CENSI - Centro de Ensino Superior de Itabira",
            "Centro de Ensino Superior do Amapá",
            "Centro de Estudos Superiores de Maceió",
            "Centro Universitário Nilton Lins",
            "CESAT - Escola de Ensino Superior Anísio Teixeira",
            "CESCAGE - Centro de Ensino Superior dos Campos Gerais",
            "CESF - Centro de Ensino Superior Cenecista de Farroupilha",
            "Cesf - Instituto de Ensino Superior Fucapi",
            "CEST - Faculdade Santa Terezinha (São Luís)",
            "CESUC - Centro de Ensino Superior de Catalão [4]",
            "CESUMAR - Centro Universitário de Maringá",
            "CESUPA - Centro Universitário do Pará",
            "CESV - Centro de Ensino Superior de Vitória",
            "CET - Centro de Educação Tecnológico",
            "CEUB - Centro Universitário de Brasília",
            "CEULJI/ULBRA - Centro Universitário Luterano de Ji-Paraná",
            "CEULP/ULBRA - Centro Universitário Luterano de Palmas",
            "CEUNSP - Centro Universitário Nossa Senhora do Patrocínio",
            "CEUT - Centro de Ensino Unificado de Teresina",
            "CIABA - Centro de Instrução Almirante Braz de Aguiar",
            "CIAGA - Centro de Instrução Almirante Graça Aranha",
            "Ciesa - Centro Universitário de Ensino Superior do Amazonas",
            "CLARETIANO - centro universitário",
            "CNECSAN - Faculdade CNEC Santo Ângelo",
            "CUEA - Centro Universitário Eaprenda Elearning",
            "CUFSA - Centro Universitário Fundação Santo André[15]",
            "CUSC - Centro Universitário São Camilo",
            "CUSC - Centro Universitário São Camilo",
            "DEVRY - DeVry João Pessoa",
            "DOMPEDRO - Faculdades Integradas Dom Pedro II",
            "Edifício da reitoria da Universidade Federal de Ouro Preto.",
            "EDUVALE - Faculdade de Ciências Sociais Aplicadas do Vale do São Lourenço",
            "EEK - Escola de Engenharia Kennedy",
            "EEP/FUMEP - Escola de Engenharia de Piracicaba[16]",
            "EEWB - Escola de Enfermagem Wenceslau Braz",
            "EMESCAM - Escola Superior de Ciências da Santa Casa de Misericórdia de Vitória",
            "EN - Escola Naval",
            "ENCE - Escola Nacional de Ciências Estatísticas",
            "ESAC - Escola Superior de Aviação Civil",
            "ESAGS - Escola Superior de Administração e Gestão",
            "ESAMAZ - Escola Superior da Amazônia",
            "Esbam - Escola Superior Batista do Amazonas",
            "ESBJ - Faculdade Maurício de Nassau",
            "ESDHC - Escola Superior Dom Helder Câmara",
            "ESEFIC - Escola Superior de Cruzeiro \"Prefeito Hamilton Vieira Mendes\"",
            "ESEFJ - Escola Superior de Educação Física de Jundiaí",
            "ESFA - Escola Superior São Francisco de Assis",
            "ESMAC - Escola Superior Madre Celeste",
            "ESMARGS - Escola Superior de Música e Artes do Rio Grande do Sul",
            "ESPM - Escola Superior de Propaganda e Marketing",
            "EST - Faculdades EST",
            "ESTÁCIO FAP - Estácio de Sá - Faculdade do Pará",
            "ESTÁCIO FIC - Faculdade Integrada do Ceará",
            "FA7 - Faculdade 7 de Setembro",
            "FAA - Faculdade Anhanguera de Anápolis",
            "FAAB - Faculdade Alfa Brasil",
            "FAACH - Faculdade Santa Rita de Chapecó",
            "FAACZ - Faculdade de Aracruz",
            "FAAM - Faculdade da Amazônia",
            "FAAMA - Faculdade Adventista da Amazônia",
            "Faao - Faculdade da Amazônia Ocidental",
            "FAAP - Fundação Armando Álvares Penteado",
            "FAAR - Faculdades Associadas de Ariquemes",
            "FABAVI - Faculdade Batista de Vitoria",
            "FABEL - Faculdade de Belém",
            "FAC - Faculdade Arquidiocesana de Curvelo",
            "FAC - Faculdade de Campina Grande",
            "FAC - Faculdades Cearenses",
            "Fac- Faculdade Católica de Anápolis",
            "FACAMP - Faculdades de Campinas",
            "FACAPA - (Faculdade Católica de Pouso Alegre)",
            "FACAR - Faculdade de Aracaju [27]",
            "FACC - Faculdade Concórdia",
            "FACCAMP - Faculdade de Campo Limpo Paulista",
            "FACCAT - Faculdades Integradas de Taquara",
            "FACDO - Faculdade Católica Dom Orione",
            "FACE - Faculdade Casa do Estudante",
            "FACE - Faculdade Evolutivo",
            "FACECA - Faculdade Cenecista de Varginha",
            "FACED - Faculdade de Ciências Contabeis de Divinópolis",
            "FACEG -Faculdade Evangelica de Goianesia",
            "FACELI - Faculdade de Ensino Superior de Linhares",
            "FACEMA - Faculdade de Ciências e Tecnologia do Maranhão (Caxias)",
            "FACENE - Faculdade de Enfermagem Nova Esperança",
            "Facene/RN - Faculdade de Enfermagem e Medicina Nova Esperança de Mossoró",
            "FACENSA - Faculdade Cenecista Nossa Senhora dos Anjos",
            "FACER - Faculdade de Ciências de Rubiataba",
            "FACERES - Faculdade de Ceres",
            "FACESM - Faculdade de Ciências Sociais Aplicadas do Sul de Minas",
            "FACETE - Faculdade de Ensino Tecnológico do Estado do Pará",
            "FACETEN - Faculdade de Ciências, Educação e Teologia do Norte do Brasil",
            "Facex - Faculdade de Ciências, Cultura e Extensão do RN",
            "FACHA - Faculdades Integradas Hélio Alonso",
            "FACI - Faculdade Ideal",
            "FACIC: A Faculdade de Ciências Humanas de Cruzeiro ",
            "FACICA - Faculdade de Ciências da Saúde de Campos Gerais",
            "FACICESP - FACULDADES INTEGRADAS ICESP - UNICESP - Brasília",
            "FACID - Faculdade Integral Diferencial",
            "FACIMED - Faculdade de Ciências Biomédicas de Cacoal",
            "FACIMP - Faculdade de Imperatriz",
            "FACIP - Faculdade Ipiranga",
            "FACIPLAC - Faculdade de Ciência e Tecnologia do Planalto Central",
            "FACIT - Faculdade de Ciências do Tocantins",
            "FACITEC - Faculdade de Ciências Sociais e Tecnológicas",
            "FACMIL - Faculdade de Administração de São José do Rio Preto",
            "FACOS - Faculdade Cenecista de Osório",
            "FACSUL -Faculdade Mato Grosso do Sul",
            "FACTO - Faculdade Católica do Tocantins",
            "FACTU - Faculdade de Ciências e Tecnologia de Unaí",
            "Faculdade Anglo - Americano [12] - Grupo Educacional",
            "Faculdade Atlântico [30]",
            "Faculdade Campo Real",
            "Faculdade Católica Nossa Senhora Das Neves",
            "Faculdade Estácio de Sergipe [21]",
            "Faculdade FAMA",
            "Faculdade Guairacá",
            "Faculdade Guarapuava",
            "Faculdade Integrada Tiradentes",
            "Faculdade Mater Christi",
            "Faculdade Maurício de Nassau - (Pólo Natal)",
            "Faculdade Meta",
            "Faculdade Pio Décimo [20]",
            "Faculdade Pitágoras",
            "Faculdade SEAMA",
            "Faculdades Cathedral",
            "Faculdades",
            "FADAF - Faculdade de Direito de Alta Floresta",
            "FADI - Faculdade de Direito de Sorocaba",
            "FADISC - Faculdades Integradas de São Carlos",
            "Fadisi - Faculdade Diocesana São José",
            "FADISMA - Faculdade de Direito de Santa Maria",
            "FADMINAS - Faculdades Integradas Adventistas de Minas Gerais",
            "FADOM - Faculdades integradas do Oeste de Minas",
            "FAE - Faculdade Anglicana de Erechim",
            "FAE - Faculdades Equipe - Sapucaia do Sul",
            "FAE - FAE Centro Universitário[7]",
            "FAEMA - Faculdade de Educação e Meio Ambiente",
            "FAESA - Faculdades Integradas Espírito-Santenses",
            "FAESNE - Faculdade de Ensino Superior do Nordeste",
            "FAEV/UNESC - Faculdade de Educação e Cultura de Vilhena",
            "FAFEM - Faculdades da Fundação de Ensino de Mococa",
            "FAFIA - Faculdade de Filosofia Ciências e Letras de Alegre",
            "FAFIC - Faculdade de Filosofía Ciências e Letras de Cajazeiras",
            "FAFIL - Faculdade de Filosofía Ciências e Letras",
            "FAG - Faculdade Guaraí",
            "FAG - Fundação Assis Gurgacz",
            "FAGAMMON - Faculdade Presbiteriana Gammon",
            "FAI - Faculdades Adamantinenses Integradas",
            "FAIBI - Faculdade de Filosofia, Ciências e Letras de Ibitinga",
            "FAJAR - Faculdade Jaguariaíva",
            "FAJAR - Faculdade Jardins [29]",
            "FAL - Faculdade de Natal",
            "Fal - Faculdade Literatus",
            "FALS - Faculdade de Ciências Aplicadas Doutor Leão Sampaio",
            "FALS - Faculdade do Litoral Sul Paulista",
            "FAM - Faculdade Antonio Meneghetti",
            "FAM - Faculdade de Americana",
            "FAMA - Faculdade Amadeus [23]",
            "FAMA - Faculdade Atenas Maranhense",
            "FAMA - Faculdade da Amazônia",
            "FAMAZ - Faculdade Metropolitana da Amazônia",
            "FAMEMA - Faculdade de Medicina de Marília",
            "FAMERP - Faculdade de Medicina de São José do Rio Preto",
            "FAMES - Faculdade De Musica do Espírito Santo \"Mauricio de Oliveira\" IFB - Instituto Federal de Brasília",
            "Fameta - Faculdade Meta",
            "FAMETRO - Faculdade Metropolitana de Fortaleza [3]",
            "Fametro - Faculdade Metropolitana de Manaus",
            "Fanec - Faculdade Natalense de Ensino e Cultura",
            "FANESE - Faculdade de Administração e Negócios de Sergipe [22]",
            "FANOR - Faculdades Nordeste",
            "FANP - Faculdade do Noroeste Paranaense",
            "FAP - Faculdade do Baixo Paranaíba (Chapadinha)",
            "FAP - Faculdade Paraibana",
            "FAP - Faculdade Paraíso do Ceará",
            "FAP - Faculdade Piauiense",
            "FAP - Faculdade Santa Rita Palmitos",
            "FAPA - Faculdade Porto Algrense",
            "FAPAL - Faculdade de Palmas",
            "FAPAN - Faculdade do Pantanal",
            "FAPAN - Faculdade Pan Amazônica",
            "FAPCOM - Faculdade Paulus de Comunicação e Tecnologia",
            "FAPECS - Instituto de Pesquisa em Ciências da Saude",
            "FAPI - Faculdades de Pinhais",
            "FARES - Faculdade Roraimense de Ensino Superior",
            "FARESC - Faculdades Integradas Santa Cruz de Curitiba",
            "FARN - Faculdade Natalense para o Desenvolvimento do Rio Grande do Norte",
            "FARO - Faculdade de Ciências Humanas, Exatas e Letras de Rondônia",
            "FARR - Faculdade Reinaldo Ramos",
            "FAS - Faculdade Ari de Sá",
            "FASAM - Faculdade Sul-Americana",
            "FASE - Faculdade da Serra",
            "FASEC - Faculdade Serra do Carmo",
            "FASEP - Faculdade Serrana",
            "FASER - Faculdade Santa Emília de Rodat",
            "FASER - Faculdade Sergipana [26]",
            "FASF - Faculdade Sagrada Família",
            "FASF - Unisa - Faculdade de Filosofia, Ciências e Letras do Alto São Francisco",
            "FASIPE - Faculdade FASIPE",
            "FASP - Faculdade São Francisco da Paraíba",
            "FATE - Faculdade Ateneu",
            "FATE - Faculdade Ateneu",
            "FATEB - Faculdade de Ciências e Tecnologia de Birigui",
            "FATEB - Faculdade de Telêmaco Borba",
            "FATEC - Faculdade de Tecnologia de João Pessoa",
            "FATEC - Faculdade de Tecnologia do Estado de São Paulo",
            "FATEC - Faculdade de Teologia e Ciências [5]",
            "FATEC Luiz Rosa - Faculdade de Tecnologia Prof. Luiz Rosa",
            "FATECPB - Faculdade de Tecnología da Paraíba",
            "FATENE - Faculdade Terra Nordeste",
            "Fatern Gama Filho - Faculdade de Excelência do Rio Grande do Norte",
            "FAVALE-UEMG- Faculdades Vale do Carangola",
            "FAVENORTE - Instituto Superior de Educação Verde Norte",
            "Favi/FACES - Faculdade do Espírito Santo",
            "FAZU - Faculdades Associadas de Uberaba",
            "FBNCTSB - Faculdade Boas Novas de Ciências Teológicas, Sociais e Biotecnológicas",
            "FCAT - Faculdade de Castanhal",
            "FCB - [Faculdade Castelo Branco] Colatina/ES.",
            "FCC - Faculdade Câmara Cascudo",
            "FCC - Faculdade Católica do Ceará",
            "FCF - Faculdade Católica de Fortaleza [2]",
            "FCG- Faculdade Campo Grande",
            "FCL - Faculdade Cásper Líbero",
            "FCM - Faculdade de Ciências Médicas de Campina Grande",
            "FCMMG - Faculdade de Ciências Médicas de Minas Gerais",
            "FCMS/JF - Faculdade de Ciências Médicas e da Saúde de Juiz de Fora",
            "FCMV - Faculdade Candido Mendes de Vitória",
            "FCRS - Faculdade Católica Rainha do Sertão",
            "FDF - Faculdade de Direito de Franca",
            "FDSBC - Faculdade de Direito de São Bernardo do Campo",
            "FDSM - Faculdade de Direito do Sul de Minas",
            "FDV - Faculdades Integradas de Vitória",
            "FEA - Fundação Educacional Araçatuba",
            "FEAD - Faculdade de Estudos Administrativos de Minas Gerais",
            "FEAPA - Faculdade de Estudos Avançados do Pará",
            "FEBASP - Centro Universitário Belas Artes de São Paulo",
            "FECAP - Fundação Escola de Comércio Álvares Penteado",
            "FECIPAR - Faculdade de Educação Ciências e Letras de Paraíso",
            "FEEVALE - Universidade Feevale",
            "FEF - Faculdade Evilásio Formiga",
            "FEF - Fundação Educacional de Fernandópolis",
            "FEI - Fundação Educacional Inaciana \"Pe. Sabóia de Medeiros\" (Faculdade de Engenharia Industrial)",
            "FEMA - Escola Técnica e Superior Machado de Assis - Santa Rosa",
            "FeMASS - Faculdade Professor Miguel Ângelo da Silva Santos - MacaéFAETERJ - Faculdade de Educação Tecnológica do Estado do Rio de Janeiro[1]",
            "FEMG - Faculdade de Engenharia de Minas Gerais",
            "FEPAR - Faculdade Evangélica do Paraná[8]",
            "FESC - Fundação de Ensino Superior de Clevelândia",
            "FESP - Faculdade de Ensino Superior da Paraíba",
            "FESP - Fundação de Ensino Superior de Passos",
            "FESPSP - Fundação Escola de Sociologia e Política de São Paulo",
            "FEST - Faculdade Santa Terezinha (Imperatriz)",
            "FESURV - Universidade de Rio Verde[5]",
            "FESVIP - Faculdade de Enfermagem São Vicente de Paula",
            "FFB - Faculdade Farias Brito",
            "FFCL - Faculdade de Filosofia Ciências e Letras de São José do Rio Pardo",
            "FFSD - Faculdade de Filosofia Santa Doroteia",
            "FGF - Faculdade Integrada da Grande Fortaleza",
            "FGV - Fundação Getúlio Vargas",
            "FGV - Fundação Getúlio Vargas",
            "FIAA - Faculdades Integradas Anglo - Americano",
            "FIAA - Faculdades Integradas Anglo - Americano",
            "FIAP - Faculdade de Administração e Informática Paulista",
            "FIAR - Faculdades Integradas de Ariquemes",
            "FIBRA - Faculdade Integrada Brasil Amazônia",
            "FIES - Faculdades Integradas Espírita",
            "FIESC - Faculdade Integrada de Ensino Superior de Colinas",
            "FIJ - Faculdades Integradas de Jacarepaguá",
            "FIMCA - Faculdades Integradas Aparício Carvalho",
            "FIO - Faculdades Integradas de Ourinhos",
            "FIP - Faculdades Integradas de Patos",
            "FIRB - Faculdades Integradas Rio Branco",
            "FIRB - Faculdades Integradas Rio Branco",
            "FISMA - Faculdade Integrada de Santa Maria",
            "FIT - Faculdade Impacta Tecnologia",
            "FIT - Faculdades Integradas do Tapajós - FIT (Santarém)",
            "FITO - Fundação Instituto Tecnológico de Osasco",
            "FJN - Faculdade de Juazeiro do Norte",
            "FJP - Fundação João Pinheiro",
            "FLAMINGO - Faculdade Flamingo",
            "FLF - Faculdade Luciano Feijão",
            "FMABC - Faculdade de Medicina do ABC",
            "FMB- Faculdade Montes Belos",
            "FMC - Faculdade de Medicina de Campos",
            "FMC - Faculdades Milton Campos",
            "FMF - Faculdade Martha Falcão",
            "FMG - Faculdade Metodista Granbery",
            "FMIT - Faculdade de Medicina de Itajubá",
            "FMJ - Faculdade de Medicina de Juazeiro do Norte",
            "FMJ - Faculdade de Medicina de Jundiaí",
            "FML - Faculdade Metropolitana Londrinense",
            "FMM - Faculdade Metropolitana de Marabá",
            "FMP - Faculdade Municipal de Palhoça",
            "FMPFM - Faculdade Municipal Professor Franco Montoro de Mogi Guaçu",
            "FMS - Faculdade Mario Schenberg",
            "FMU - Centro Universitário das Faculdades Metropolitanas Unidas",
            "FNC - Faculdade Nossa Cidade",
            "FOC - Faculdades Oswaldo Cruz",
            "Fom - Faculdade de Odontologia de Manaus",
            "FPA - Faculdade Pan Americana",
            "FPAS - Faculdade Pitágoras de Administração Superior",
            "FPB - Faculdade Internacional da Paraíba",
            "FPB - Faculdade Potiguar da Paraíba",
            "FPMG - Faculdade Promove de Minas Gerais",
            "FPP - Faculdades Pequeno Príncipe",
            "FPPD - Faculdade Paraibana de Processamento de Dados",
            "FPU - Faculdade Politécnica de Uberlândia",
            "FRB - Faculdades Integradas Rio Branco",
            "FSA - Faculdade Santo Agostinho",
            "FSA - Faculdades Santo Agostinho",
            "FSB/RJ - Faculdade de São Bento do Rio de Janeiro",
            "FSDB - Faculdade Salesiana Dom Bosco",
            "FSG - Faculdade da Serra Gaúcha",
            "FSL - Faculdade São Lucas",
            "FSL - Faculdade São Luís",
            "FSLF - Faculdade São Luis de França [24]",
            "FSM - Faculdade Santa María",
            "FSMA - Faculdade Salesiana de Macaé",
            "FT - Faculdade Táhirih",
            "FTA - Faculdade de Tecnologia Apoena",
            "FTB - Faculdades Integradas da Terra de Brasília Descredenciada (Despacho nº 59-SESu/Mec, de 02/05/2011)",
            "FTEC - Faculdade de Tecnologia TecBrasil",
            "FTESM- Fundação Técnico Educacional Souza Marques",
            "FTML - Faculdade de Teologia Metodista Livre",
            "FTT - Faculdade de Tecnologia Termomecânica",
            "FUCAPE - Fundação Instituto Capixaba de Pesquisas em Contabilidade, Economia e Finanças",
            "FUMEC - Fundação Mineira de Educação e Cultura",
            "FUNCESI - Fundação Comunitária de Ensino Superior de Itabira",
            "FUNEC - Faculdades Integradas de Santa Fé do Sul",
            "FUNEDI - Fundação Educacional de Divinópolis",
            "FUNENSEG - Escola Nacional de Seguros",
            "FUNJOB - Faculdade de Medicina de Barbacena",
            "Funorte - Faculdades Unidas do Norte de Minas",
            "FURB - Fundação Universidade Regional de Blumenau",
            "FURG - Universidade Federal do Rio Grande",
            "FVJ - Faculdade Vale do Jaguaribe",
            "FZP - Faculdade Zumbi dos Palmares",
            "IACS - Instituto Adventista Cruzeiro do Sul",
            "Iaes - Faculdade do Amazonas",
            "IAESUP- Faculdades e Colégio Aphonsiano",
            "Ibmec - Ibmec (Instituição de Ensino)",
            "IBMR - Centro Universitário Hermínio da Silveira",
            "ICF - Instituto Camillo Filho",
            "IDEAU - Instituto de Desenvolvimento Educacional do Alto Uruguai - Getúlio Vargas",
            "IEPO - Instituto de Ensino e Pesquisa Objetivo",
            "IERSA - Instituto Educacional Raimundo Sá (Faculdade R. Sá)",
            "Iesacre - Instituição de Ensino Superior do Acre",
            "IESAM - Instituto de Ensinos Superiores da Amazônia",
            "IESAP",
            "IESB - Instituto de Educação Superior de Brasília",
            "IESF - Instituto de Ensino Superior da Fupesp",
            "IESF - Instituto de Ensino Superior de Fortaleza",
            "IESF - Instituto de Ensino Superior Franciscano (Paço do Lumiar)",
            "IESP - Instituto de Educação Superior da Paraíba",
            "IESP - Instituto de Educação Superior de Patrocínio",
            "IF Goiano - Instituto Federal Goiano",
            "Ifac - Instituto Federal do Acre",
            "Ifal - Instituto Federal de Alagoas",
            "Ifam - Instituto Federal do Amazonas",
            "Ifap - Instituto Federal do Amapá",
            "IFCE - Instituto Federal do Ceará",
            "IFES - Instituto Federal do Espírito Santo",
            "IFF - Instituto Federal Fluminense",
            "IFFarroupilha - Instituto Federal Farroupilha",
            "IFG - Instituto Federal de Goiás",
            "IFMA - Instituto Federal do Maranhão",
            "IFMG - Instituto Federal de Minas Gerais",
            "IFMS - Instituto Federal de Mato Grosso do Sul",
            "IFMT - Instituto Federal do Mato Grosso",
            "IFNMG - Instituto Federal do Norte de Minas Gerais",
            "IFPA - Instituto Federal do Pará",
            "IFPB - Instituto Federal da Paraíba",
            "IFPI - Instituto Federal do PiauíUESPI - Universidade Estadual do Piauí",
            "IFPR - Instituto Federal do Paraná",
            "IFRJ - Instituto Federal do Rio de Janeiro",
            "IFRN - Instituto Federal do Rio Grande do Norte",
            "IFRO - Instituto Federal de Rondônia",
            "IFRR - Instituto Federal de RoraimaEstácio Atual",
            "IFRS - Instituto Federal do Rio Grande do Sul",
            "IFS - Instituto Federal de Sergipe",
            "IFSM - Instituto Federal do Sudeste de Minas",
            "IFSP - Instituto Federal de Educação, Ciência e Tecnologia de São Paulo",
            "IFSul - Instituto Federal Sul-rio-grandense",
            "IFSUM - Instituto Federal do Sul de Minas",
            "IFTM - Instituto Federal do Triângulo Mineiro",
            "IFTO - Instituto Federal do Tocantins",
            "ILES/ULBRA - Instituto Luterano de Ensino Superior de Porto Velho",
            "IME - Instituto Militar de Engenharia",
            "IMES Catanduva - Instituto Municipal de Ensino Superior de Catanduva",
            "IMESA - Instituto Municipal de Ensino Superior de Assis",
            "IMESB - Instituto Municipal de Ensino Superior de Bebedouro Victório Cardassi",
            "IMESSM - Instituto Municipal de Ensino Superior de São Manuel",
            "IMMES - Instituto Matonense Municipal de Ensino Superior",
            "IMMES",
            "IMT - Instituto Mauá de Tecnologia",
            "IMT - Instituto Mauá de Tecnologia",
            "INESC - Instituto de Ensino Superior Cenecista",
            "INFNET - Instituto Infnet[3]",
            "INPER - Insituto Paraibano de Ensino Renovado",
            "INSJAR - Instituto Jordão de Arruda",
            "Insper - Instituto de Ensino e Pesquisa",
            "Instituto de Educação Antonino Freire em Teresina.",
            "Instituto Federal Catarinense",
            "Instituto Federal de Santa Catarina",
            "Institutos e Academias",
            "INTA - Instituto Superior de Teologia Aplicada",
            "IPA - Centro Universitário Metodista do Instituto Porto Alegre",
            "IPOG - Instituto de Pós-Graduação (Pólo Natal)",
            "IPOG - Instituto de Pós-Graduação & Graduação",
            "IPOG- Instituto de Pós-Graduação",
            "IPTAN - Instituto de Ensino Superior Presidente Tancredo Neves",
            "ISEAF - Instituto Superior de Educação Antonino Freire",
            "ISEC - Insituto Superior de Educação de Cajazeiras",
            "ISEC - Instituto Superior de Educação de Campos Gerais",
            "ITA - Instituto Tecnológico de Aeronáutica",
            "ITE - Instituição Toledo de Ensino",
            "ITPAC - Instituto Tocantinense Presidente Antônio Carlos",
            "ITPAC de Porto Nacional - Instituto Tocantinense Presidente Antônio Carlos de Porto Nacional",
            "IUESO- Faculdades Objetivo",
            "JAPI - Faculdade Japi",
            "LA SALLE - Faculdade La Salle",
            "Laboratório Central de Petróleo e Gás Natural da Universidade Federal do Rio Grande do Norte.",
            "LUMEN FAC - Faculdade de Ciências Contábeis Luiz Mendes",
            "LUMEN FAC - Faculdade de Ciências Médicas da Paraíba",
            "MACK - Universidade Presbiteriana Mackenzie",
            "Mackenzie Rio -Faculdade Presbiteriana Mackenzie RJ",
            "MARQUÊS - Instituto de Educação Cenecista Marquês de Herval",
            "Militares",
            "MULTIVIX- Faculdade Brasileira",
            "Municipais - em Santa Catarina, contituidas sob a forma de Fundações",
            "Novafapi - Faculdade de Saúde, Ciências Humanas e Tecnológicas do Piauí",
            "NovaUnesc",
            "OPET - Organização Paranaense de Ensino Técnico",
            "PIO XII- Faculdade de Estudos Sociais do Espírito Santo",
            "PUC - Pontifícia Universidade Católica de Goiás",
            "PUC-Campinas - Pontifícia Universidade Católica de Campinas (PUCCAMP, antigamente)",
            "PUCMG - Pontifícia Universidade Católica de Minas Gerais",
            "PUCPR - Pontifícia Universidade Católica do Paraná",
            "PUCRIO - Pontifícia Universidade Católica do Rio de Janeiro",
            "PUCRS - Pontifícia Universidade Católica do Rio Grande do Sul",
            "PUCSP - Pontifícia Universidade Católica de São Paulo",
            "REDENTOR - Sociedade Universitária Redentor - Faculdade Redentor",
            "SABERES- Faculdade Saberes",
            "SECAL - Faculdade Santa Amélia",
            "SECAL - Faculdade Santa Amélia",
            "SENAC - Centro Universitário Senac - São Paulo",
            "SENAC - Faculdade Senac - Distrito Federal",
            "SENAC - Faculdade Senac - Rio Grande do Sul",
            "SENAC - Faculdade Senac - Santa Catarina",
            "SENAC - Faculdade Senac Rio de Janeiro",
            "SJT - Instituição Educacional São Judas Tadeu",
            "SLMANDIC - Faculdade de Odontologia e Centro de Pesquisas Odontológicas São Leopoldo Mandic",
            "SOCIESC - Sociedade Educacional de Santa Catarina",
            "TECMED - Faculdade de Tecnologia Tecmed",
            "UAM - Universidade Anhembi Morumbi",
            "UBC - Universidade Braz Cubas",
            "UBM - Centro Universitário de Barra Mansa",
            "UCAM - Universidade Cândido Mendes",
            "UCB - Universidade Castelo Branco",
            "UCB - Universidade Católica de Brasília",
            "UCDB - Universidade Católica Dom Bosco",
            "UCESP - Faculdade União Cultural do Estado de São Paulo",
            "UCL - Faculdade do Centro Leste",
            "UCP - Faculdades do Centro do Paraná",
            "UCP - Universidade Católica de Petrópolis",
            "UCPEL - Universidade Católica de Pelotas",
            "UCS - Universidade de Caxias do Sul",
            "UDESC - Universidade do Estado de Santa Catarina",
            "UDF - Centro Universitário do Distrito Federal",
            "Uea - Universidade do Estado do Amazonas",
            "Ueap - Universidade Estadual do Amapá",
            "UEB - Universidade Eletrônica do Brasil",
            "UECE - Universidade Estadual do Ceará",
            "UEL - Universidade Estadual de Londrina",
            "UEM - Universidade Estadual de Maringá",
            "UEMA - Universidade Estadual do Maranhão",
            "UEMG - Universidade do Estado de Minas Gerais",
            "UEMS - Universidade Estadual do Mato Grosso do Sul",
            "UENF - Universidade Estadual do Norte Fluminense",
            "UENP - Universidade Estadual do Norte do Paraná",
            "UEPB - Universidade Estadual da Paraíba",
            "UEPG - Universidade Estadual de Ponta Grossa",
            "UERGS - Universidade Estadual do Rio Grande do Sul",
            "UERJ - Universidade do Estado do Rio de Janeiro",
            "UERN - Universidade do Estado do Rio Grande do Norte",
            "UERR - Universidade Estadual de RoraimaUFRR - Universidade Federal de Roraima",
            "UEZO - Universidade Estadual da Zona Oeste[2]",
            "UFABC - Universidade Federal do ABC",
            "Ufac - Universidade Federal do AcreUninorte - União Educacional do Norte",
            "Ufal - Universidade Federal de Alagoas",
            "Ufam - Universidade Federal do Amazonas",
            "UFC - Universidade Federal do Ceará",
            "UFCA - Universidade Federal do Cariri",
            "UFCG - Universidade Federal de Campina Grande",
            "UFCSPA - Universidade Federal de Ciências da Saúde de Porto Alegre",
            "UFERSA - Universidade Federal Rural do Semi-Árido",
            "UFES - Universidade Federal do Espírito Santo",
            "UFF - Universidade Federal Fluminense",
            "UFFS - Universidade Federal da Fronteira do Sul",
            "UFFS - Universidade Federal da Fronteira do Sul",
            "UFFS - Universidade Federal da Fronteira Sul",
            "UFG - Universidade Federal de Goiás",
            "UFGD - Universidade Federal da Grande Dourados",
            "UFJF - Universidade Federal de Juiz de Fora",
            "UFLA - Universidade Federal de Lavras",
            "UFMA - Universidade Federal do Maranhão",
            "UFMG - Universidade Federal de Minas Gerais",
            "UFMS - Universidade Federal do Mato Grosso do Sul",
            "UFMT - Universidade Federal de Mato Grosso",
            "UFOP - Universidade Federal de Ouro Preto",
            "UFOPA - Universidade Federal do Oeste do Pará",
            "UFPA - Universidade Federal do Pará",
            "UFPAN - Universidade Federal do Pantanal",
            "UFPB - Universidade Federal da Paraíba",
            "UFPEL - Universidade Federal de Pelotas",
            "UFPI - Universidade Federal do Piauí",
            "UFPR - Universidade Federal do Paraná",
            "UFRA - Universidade Federal Rural da Amazônia",
            "UFRGS - Universidade Federal do Rio Grande do Sul",
            "UFRJ - Universidade Federal do Rio de Janeiro",
            "UFRN - Universidade Federal do Rio Grande do Norte",
            "UFRRJ - Universidade Federal Rural do Rio de Janeiro",
            "UFS - Universidade Federal de Sergipe",
            "UFSC - Universidade Federal de Santa Catarina",
            "UFSCar - Universidade Federal de São Carlos",
            "UFSJ - Universidade Federal de São João del-Rei",
            "UFSM - Universidade Federal de Santa Maria",
            "UFT - Universidade Federal do Tocantins",
            "UFTM - Universidade Federal do Triângulo Mineiro",
            "UFU - Universidade Federal de Uberlândia",
            "UFV - Universidade Federal de Viçosa",
            "UFVJM - Universidade Federal dos Vales do Jequitinhonha e Mucuri",
            "UGB - Centro Universitário Geraldo Di Biase",
            "UGS - Universidade Gama e Souza",
            "UIT - Universidade de Itaúna",
            "ULBRA - Universidade Luterana do Brasil - EAD",
            "ULBRA - Universidade Luterana do Brasil (Polo Natal)",
            "ULBRA - Universidade Luterana do Brasil",
            "ULBRA - Universidade Luterana do Brasil",
            "ULBRA - Universidade Luterana do Brasil",
            "UMC - Universidade de Mogi das Cruzes",
            "UMESP - Universidade Metodista de São Paulo",
            "UNA - Centro Universitário UNA",
            "UNAERP - Universidade de Ribeirão Preto",
            "UNAES - Centro Universitário de Campo Grande",
            "UNAMA - Universidade da Amazônia",
            "UNASP - Centro Universitário Adventista de São Paulo",
            "UnB - Universidade de BrasíliaESCS - Escola Superior de Ciências da Saúde",
            "UNC - Universidade do Contestado",
            "Uncisal - Universidade Estadual de Ciências da Saúde de Alagoas",
            "UNDB - Unidade de Ensino Superior Dom Bosco (São Luís)",
            "Uneal - Universidade Estadual de Alagoas",
            "UNEMAT - Universidade do Estado de Mato Grosso",
            "UNERJ - Centro Universitário de Jaraguá do Sul",
            "UNESA - Universidade Estácio de Sá",
            "UNESA - Universidade Estácio de Sá",
            "UNESA - Universidade Estácio de Sá",
            "UNESC - Centro Universitário do Espírito Santo",
            "UNESC - Faculdades Integradas de Cacoal",
            "UNESC - Universidade do Extremo Sul Catarinense",
            "UNESP - Universidade Estadual Paulista",
            "UNESPAR - Universidade Estadual do Paraná",
            "UNEST - União Educacional de Ensino Superior do Médio Tocantins",
            "UNG - Universidade de Guarulhos",
            "Uni-FACEF - Centro Universitário de Franca",
            "UniABC - Universidade do Grande ABC",
            "UNIABEU Centro Universitário",
            "UNIANDRADE - Centro Universitário Campos de Andrade",
            "UNIANHANGUERA - Anhanguera Educacional S.A.",
            "Unianhanguera- Universidade Anhanguera",
            "UNIARA - Centro Universitário de Araraquara",
            "UNIARAXÁ - Centro Universitário do Planalto de Araxá",
            "UNIARP - Universidade Alto Vale do Rio do Peixe",
            "UNIASSELVI- Centro Universitário Leonardo da Vinci",
            "UNIBAN - Universidade Bandeirante de São Paulo",
            "UNIBAVE - Universidade Barriga Verde",
            "UNIBERO - Centro Universitário Anhanguera de São Paulo",
            "UNIBH - Centro Universitário de Belo Horizonte",
            "UNIBRATEC - Faculdade de Tecnologia Ibratec",
            "UNIC - Universidade de Cuiabá",
            "UNICAMP - Universidade Estadual de Campinas",
            "UNICAMPO - Faculdade União de Campo Mourão[10]",
            "UNICARIOCA - Centro Universitário Carioca",
            "UNICASTELO - Universidade Camilo Castelo Branco",
            "UNICENTRO - Universidade Estadual do Centro-Oeste",
            "UNICEP - Centro Universitário Central Paulista",
            "UNICERP - Centro Universitário do Cerrado - Patrocínio",
            "UNICEUMA - Centro Universitário do Maranhão (São Luís)",
            "UNICHRISTUS",
            "UniCOC - Sistema COC de Educação",
            "UNICRUZ - Universidade de Cruz Alta",
            "UNICSUL - Universidade Cruzeiro do Sul",
            "UNICURITIBA - Centro Universitário Curitiba",
            "UNIDERP - Universidade para o Desenvolvimento do Estado e Região do Pantanal",
            "UNIDESC - Centro Universitário de Desenvolvimento do Centro Oeste",
            "UniEvangelica- Universidade Evangelica",
            "UNIFAE - Centro Universitário das Faculdades Associadas de Ensino",
            "UNIFAI - Centro Universitário Assunção",
            "UNIFAL - Universidade Federal de Alfenas",
            "Unifap - Universidade Federal do Amapá",
            "UNIFASC - Faculdade Santa Rita de Cássia",
            "UNIFEB - Centro Universitário da Fundação Educacional de Barretos[18]",
            "UNIFEBE - Centro Universitário de Brusque ",
            "UNIFEI - Universidade Federal de Itajubá",
            "UNIFEMM - Centro Universitário de Sete Lagoas \"Monsenhor Messias\"",
            "UNIFENAS - Universidade de Alfenas \"José do Rosário Vellano\"",
            "UNIFEOB - Centro Universitário da Fundação de Ensino Octávio Bastos",
            "UNIFESP - Universidade Federal de São Paulo",
            "UNIFESSPA - Universidade Federal do Sul e Sudeste do ParáUEPA - Universidade do Estado do Pará",
            "UNIFIEO - Centro Universitário FIEO",
            "UNIFIL - Centro Universitário Filadélfia[9]",
            "UNIFOA - Centro Universitário de Volta Redonda",
            "UNIFOR- Universidade de Fortaleza",
            "UNIFORMG - Centro Universitário de Formiga",
            "UNIFRA - Centro Universitário Franciscano",
            "UNIFRAN - Universidade de Franca",
            "UNIGRAN - Centro Universitário da Grande Dourados",
            "UNIGRANRIO - Universidade do Grande Rio",
            "UNIJIPA -Faculdade Panamericana de Ji-Paraná",
            "UNIJUÍ - Universidade Regional do Noroeste do Estado do Rio Grande do Sul",
            "UNILA - Universidade Federal da Integração Latino-Americana",
            "UNILAB - Universidade Federal de Integração Luso-Afro-Brasileira",
            "UNILAGO - União das Faculdades dos Grandes Lagos[19]",
            "UNILASALLE-RJ - Centro Universitário La Salle - RJ[4]",
            "UNILAVRAS - Centro Universitário de Lavras",
            "UNILESTE/MG - Centro Universitário do Leste de Minas Gerais",
            "UNIMAR - Universidade de Marília",
            "UNIMEP - Universidade Metodista de Piracicaba",
            "UNIMES - Universidade Metropolitana de Santos",
            "UNIMONTE - Centro Universitário Monte Serrat",
            "UNIMONTES - Universidade Estadual de Montes Claros",
            "UNINASSAU - Faculdade Maurício de Nassau[31]",
            "UNINGÁ - Faculdade Ingá",
            "Uninorte - Centro Universitário do Norte",
            "UNINOVE - Universidade Nove de Julho",
            "UNINTER - Grupo Educacional Uninter",
            "UNIOESTE - Universidade Estadual do Oeste do Paraná",
            "Unip - Universidade Paulista",
            "UNIP - Universidade Paulista",
            "UNIP - Universidade Paulista",
            "UNIP - Universidade Paulista",
            "UNIP - Universidade Paulista",
            "UNIP - Universidade Paulista",
            "UNIP - Universidade Paulista[13]",
            "UNIPAC - Universidade Presidente Antônio Carlos",
            "UNIPAM - Centro Universitário de Patos de Minas",
            "UNIPAMPA - Universidade Federal do Pampa",
            "UNIPAR - Universidade Paranaense",
            "UNIPB - Faculdade Unida da Paraíba",
            "UNIPÊ - Centro Universitário de João Pessoa",
            "UNIPLAC - Universidade do Planalto Catarinense",
            "UNIPLAN - Centro Universitário Planalto do Distrito Federal",
            "UNIR - Universidade Federal de Rondônia",
            "UNIRB - Faculdade Serigy [28]",
            "UnirG - Centro Universitário UnirG",
            "UNIRIO - Universidade Federal do Estado do Rio de Janeiro",
            "UNIRITTER - Centro Universitário Ritter dos Reis",
            "UNIRITTER - Centro Universitário Ritter dos Reis",
            "UNIRON - Faculdade Interamericana de Porto Velho",
            "UNIRONDON - Centro Universitário Cândido Rondon",
            "UNIRP - Centro Universitário de Rio Preto",
            "UniRV - Universidade de Rio Verde -www.unirv.edu.br/UEG - Universidade Estadual de Goiás",
            "UNISA - Universidade Santo Amaro[17]",
            "UNISAL - Centro Universitário Salesiano de São Paulo",
            "UNISALESIANO - Centro Universitário Católico Salesiano Auxilium",
            "Unisalle - Faculdade La Salle",
            "UNISANT'ANNA - Centro Universitário Sant'Anna",
            "UNISANTA - Universidade Santa Cecília",
            "UNISANTOS - Universidade Católica de Santos",
            "UniSãopaulo - Instituto São Paulo de Formação e Especialização Profissional",
            "UNISC - Universidade de Santa Cruz do Sul",
            "UNISEB - Centro Universitário Estácio UniSEB - Brasília",
            "UNISEB - Centro Universitário Estácio UniSEB -São Paulo",
            "UNISEP - União de Ensino do Sudoeste do Paraná [11]",
            "UNISINOS - Universidade do Vale do Rio dos Sinos",
            "UNISO - Universidade de Sorocaba",
            "UNISUAM - Centro Universitário Augusto Motta",
            "UNISUL - Universidade do Sul de Santa Catarina",
            "Unit - Universidade Tiradentes",
            "UNITAU - Universidade de Taubaté",
            "UNITINS - Fundação Universidade do Tocantins",
            "UNITRI - Centro Universitário do Triângulo",
            "UNIUBE - Universidade de Uberaba",
            "UNIUOL - Faculdade de Tecnologia do Uniuol",
            "UNIVAG - Centro Universitário de Várzea Grande",
            "UNIVALE - Universidade Vale do Rio Doce",
            "UNIVALI - Universidade do Vale do Itajaí",
            "UNIVAP - Universidade do Vale do Paraíba",
            "UNIVAR - Universidades Unidas do Vale do Araguaia-Barra do Garças",
            "UNIVAS - Universidade do Vale do Sapucaí",
            "UNIVATES - Centro Universitário UNIVATES",
            "Univel - União Educacional de Cascavel",
            "UNIVERCIDADE - Centro Universitário da Cidade do Rio de Janeiro",
            "UNIVERSIDADE LA SALLE",
            "UNIVERSITAS - Centro Universitário de Itajubá",
            "UNIVERSO - Universidade Salgado de Oliveira",
            "UNIVERSO - Universidade Salgado de Oliveira",
            "UNIVERSO - Universidade Salgado de Oliveira",
            "Univesp - Universidade Virtual do Estado de São Paulo",
            "UNIVIÇOSA - União de Ensino Superior de Viçosa - Univiçosa",
            "UNIVILLE - Universidade da Região de Joinville",
            "UNIVIMA - Universidade Virtual do Maranhão",
            "UNOCHAPECÓ - Universidade Comunitária Regional de Chapecó",
            "UNOESC - Universidade do Oeste de Santa Catarina",
            "UNOESTE - Universidade do Oeste Paulista",
            "UNOPAR - Aracaju Universidade Norte do Paraná [25]",
            "UNOPAR - universidade á distancia do norte do Paraná",
            "UNOPAR - Universidade do Norte do Paraná",
            "UNOPAR - Universidade Norte do Paraná (Polo Natal)",
            "UNOPAR - Universidade Norte do Paraná",
            "UNORP - Centro Universitário do Norte Paulista",
            "UNP - Universidade Potiguar",
            "UP - Universidade Positivo",
            "UPA - Universidade Patativa do Assaré",
            "UPF - Universidade de Passo Fundo",
            "UPIS - União Pioneira de Integração Social",
            "URCA - Universidade Regional do Cariri",
            "URCAMP - Universidade da Região da Campanha",
            "URI - Universidade Regional Integrada do Alto Uruguai e das Missões",
            "USCS - Universidade Municipal de São Caetano do Sul",
            "USE - Universidade Estadual de Sergipe",
            "USF - Universidade São Francisco",
            "USJ - Universidade Municipal de São José",
            "USJT - Universidade São Judas Tadeu",
            "USP - Universidade de São Paulo",
            "USS - Universidade Severino Sombra",
            "USU - Universidade Santa Úrsula",
            "UTFPR - Universidade Tecnológica Federal do Paraná",
            "UTP - Universidade Tuiuti do Paraná",
            "UVA - Universidade Estadual Vale do Acaraú",
            "UVA - Universidade Veiga de Almeida",
            "UVV - Universidade Vila Velha",
            "Outra"
    );

    public static final List<String> courses = Arrays.asList(
            "Administração",
            "Agrimensura",
            "Agroecologia",
            "Agroindústria",
            "Agronomia (ou Engenharia agronômica)",
            "Análise e Desenvolvimento de Sistemas",
            "Antropologia",
            "Aquacultura",
            "Arqueologia",
            "Arquitetura",
            "Arquivística",
            "Artes Cênicas",
            "Artes Visuais",
            "Astronomia",
            "Automação Industrial",
            "Biblioteconomia",
            "Biocombustíveis",
            "Bioengenharia",
            "Biofísica",
            "Biologia marinha",
            "Biologia",
            "Biomedicina",
            "Biotecnologia",
            "Botânica",
            "Cafeicultura",
            "Ciência & Tecnologia",
            "Ciência da Computação",
            "Ciência dos Alimentos",
            "Ciência dos materiais",
            "Ciência Política (ou Ciências do Estado)",
            "Ciências Aeronáuticas",
            "Ciências Agrárias",
            "Ciências Ambientais",
            "Ciências Atuariais",
            "Ciências Biológicas",
            "Ciências Biomoleculares",
            "Ciências Contábeis",
            "Ciências da Saúde",
            "Ciências do Meio Aquático",
            "Ciências Humanas",
            "Ciências Matemáticas da Terra",
            "Ciências Naturais",
            "Ciências Náuticas",
            "Ciências Sociais Licenciatura",
            "Cinema",
            "Comércio Exterior",
            "Comunicação social",
            "Construção de Edifícios",
            "Construção de Estradas",
            "Construção Naval",
            "Cooperativismo",
            "Cosmetologia",
            "Dança",
            "Defesa e Gestão Estratégica Internacional",
            "Desenho Industrial",
            "Design de Interiores",
            "Design de Jogos Digitais",
            "Design de Moda",
            "Design de produto",
            "Design gráfico",
            "Direito",
            "Drenagem e Irrigação",
            "Ecologia",
            "Economia Doméstica",
            "Economia",
            "Editoração",
            "Educação Artística",
            "Educação do Campo",
            "Educação física",
            "Energias Renováveis",
            "Enfermagem",
            "Engenharia aeroespacial",
            "Engenharia aeronáutica",
            "Engenharia Agrícola",
            "Engenharia Ambiental",
            "Engenharia biomédica",
            "Engenharia Cartográfica (ou Engenharia geográfica)",
            "Engenharia Civil",
            "Engenharia de Alimentos",
            "Engenharia de Computação",
            "Engenharia de controle e automação",
            "Engenharia de manufatura",
            "Engenharia de Materiais",
            "Engenharia de Minas",
            "Engenharia de Pesca",
            "Engenharia de Petróleo",
            "Engenharia de Produção",
            "Engenharia de Sistemas Eletrônicos",
            "Engenharia de Software",
            "Engenharia de Tecidos",
            "Engenharia de Telecomunicações",
            "Engenharia Elétrica (ou Engenharia de Energia )",
            "Engenharia Física",
            "Engenharia Florestal",
            "Engenharia geológica",
            "Engenharia Industrial Madeireira",
            "Engenharia Mecânica",
            "Engenharia Mecatrônica",
            "Engenharia Metalúrgica",
            "Engenharia Militar",
            "Engenharia Naval e Oceânica",
            "Engenharia Nuclear",
            "Engenharia Química",
            "Engenharia Sanitária",
            "Engenharia Têxtil",
            "Enologia",
            "Escultura",
            "Esporte e Lazer",
            "Estatística",
            "Eventos",
            "Farmácia (ou Bioquímica)",
            "Filosofia",
            "Física computacional",
            "Física médica",
            "Física",
            "Fisioterapia",
            "Fonoaudiologia",
            "Fotografia",
            "Fruticultura",
            "Gastronomia",
            "Geofísica",
            "Geografia",
            "Geologia",
            "Geoprocessamento e Sensoriamento Remoto",
            "Gerontologia",
            "Gestão Ambiental",
            "Gestão Comercial",
            "Gestão da Qualidade",
            "Gestão da Tecnologia da Informação",
            "Gestão de Petróleo e Gás",
            "Gestão de Recursos Hídricos",
            "Gestão de Segurança Privada",
            "Gestão do Agronegócio",
            "Gestão Financeira",
            "Gestão Hospitalar",
            "Gestão Portuária",
            "Gestão Pública",
            "Gravurismo",
            "História da Arte",
            "História",
            "Horticultura",
            "Hotelaria",
            "Informática biomédica",
            "Informática",
            "Jornalismo",
            "Letras",
            "Linguística",
            "Logística",
            "Manutenção Industrial",
            "Matemática Aplicada",
            "Matemática computacional",
            "Matemática",
            "Mecatrônica e Mecânica de Precisão",
            "Medicina veterinária",
            "Medicina",
            "Meliponicultura",
            "Mercadologia",
            "Meteorologia",
            "Microbiologia e Imunologia",
            "Mineração",
            "Museologia",
            "Música",
            "Nanotecnologia",
            "Naturologia",
            "Negócios Imobiliários",
            "Neurociência",
            "Nutrição",
            "Oceanografia (arcaicamente referido como Ciência dos Mares)",
            "Odontologia",
            "Oftálmica",
            "Ordenamento do Território",
            "Paisagismo",
            "Pedagogia",
            "Pintura",
            "Processamento de Dados",
            "Processos Escolares",
            "Processos Metalúrgicos",
            "Produção Audiovisual (popularmente referido como Rádio & TV, e mais arcaicamente como Radialismo)",
            "Produção Cultural",
            "Produção de Aguardente",
            "Produção de Laticínios",
            "Produção de Materiais Plásticos",
            "Produção Fonográfica",
            "Produção Sucroalcooeira",
            "Produção Têxtil",
            "Projetos de Estruturas Aeronáuticas",
            "Psicologia",
            "Publicidade & Propaganda",
            "Química ambiental",
            "Química industrial",
            "Química",
            "Quiropraxia",
            "Radiologia",
            "Recursos Humanos",
            "Redes de Computadores",
            "Redes de Telecomunicações",
            "Relações Internacionais",
            "Relações Públicas",
            "Saneamento Ambiental",
            "Saúde Coletiva",
            "Secretariado",
            "Segurança da Informação",
            "Segurança no Trabalho",
            "Segurança Pública",
            "Serviço Social",
            "Silvicultura",
            "Sistemas Biomédicos",
            "Sistemas Biomédicos",
            "Sistemas de Informação",
            "Sistemas de Navegação Fluvial",
            "Sistemas Elétricos",
            "Sistemas Embarcados",
            "Sistemas para Internet",
            "Sociologia",
            "Teatro",
            "Telemática",
            "Teologia",
            "Terapia ocupacional",
            "Transporte Aéreo",
            "Transporte Terrestre",
            "Turismologia",
            "Urbanismo",
            "Zootecnia",
            "Outro"
    );

    public static final List<String> jobs = Arrays.asList(
            "Administrador",
            "Estagiário",
            "Estudante",
            "Financeiro",
            "Professor",
            "Reitor",
            "Secretário",
            "Outro"
    );

    public static final List<String> ageRanges = Arrays.asList(
            "0 a 10",
            "11 a 20",
            "21 a 30",
            "31 a 40",
            "41 a 50",
            "51 a 60",
            "61 a 70",
            "71 a 80",
            "81 a 90",
            "91 a 100",
            "101 e acima"
    );

}
